---
- name: Installation des runners pour Gitlab CI
  hosts: runner
  remote_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3

    external_url: "http://192.168.0.104:8088"

    user: gitlab-runner

    # If the installation fail chances are that you did not override this variable
    token: "P8A8uhCFgKzMPjfRQ8mp"

    docker_image: "alpine:latest"

    docker_compose_version: "1.29.1"
    docker_compose_path: /usr/local/bin/docker-compose

  roles:
    - utils
    - user
    - runner
    - docker
