---
- name: Installation Nginx
  become: yes
  apt: name=nginx state=latest

- name: Démmarage du service Nginx
  become: yes
  service: name=nginx state=started enabled=true

- name: Supprimer default.conf sites-enabled
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx reload

- name: Création du dossier
  become: yes
  file: path=/home/{{ user }}/{{ domain }} state=directory owner={{ user }}

- name: Clonage du site {{ domain }} depuis {{ repo }}
  become: yes
  git: dest=/home/{{ user }}/{{ domain }} key_file="~/.ssh/id_rsa_api" accept_hostkey=yes clone=yes repo={{ repo }} version=feat-deploy force=yes

- name: Création du dossier {{ domain }} dans le répertoire www
  become: yes
  file: path=/var/www/{{ domain }} state=directory

- name: Création du dossier logs Nginx
  become: yes
  file: path=/home/{{ user }}/logs state=directory
 
- name: Lien vers www
  become: yes
  file: src=/home/{{ user }}/{{ domain }}/{{ api_consultation_folder }} dest=/var/www/{{ domain }}/{{ api_consultation_folder }} state=link force=yes

- name: Modification des droits du dossier {{ api_consultation_folder }}
  file: dest=/var/www/{{ domain }} state=directory mode=777 recurse=yes

- name: Création de la configuration Nginx
  template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ domain }}

- name: Activation du domain {{ domain }}
  file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
  notify: nginx reload
